export const MAP_COLORS = {
  selection: {
    point: '#8B5CF6',
    pointStroke: '#EDE9FE',
    label: '#C4B5FD',
    labelHalo: '#FFFFFF',
  },
  boundaries: {
    line: '#A78BFA',
    fill: '#C4B5FD',
    fillOpacity: 0.05,
    lineOpacity: 0.8,
    selectedLine: '#E9D5FF',
    selectedFill: '#C4B5FD',
    selectedFillOpacity: 0.12,
    selectedLineWidth: 3.2,
    selectedLineOpacity: 1,
    connectedLine: '#C4B5FD',
    connectedFill: '#DDD6FE',
    connectedFillOpacity: 0.05,
    connectedLineWidth: 2.1,
    connectedLineOpacity: 0.72,
    baseLine: '#A78BFA',
    baseFillOpacity: 0,
    baseLineWidth: 0.9,
    baseLineOpacity: 0.18,
  },
  points: {
    ltla: '#8B5CF6',
    msoa: '#3B82F6',
    stroke: '#FFFFFF',
    ltlaOpacity: 0.35,
    msoaOpacity: 0.28,
    strokeOpacity: 0.45,
    strokeWidth: 0.8,
  },
} as const;
